Feat/create csv reader
Kyonggi-Univ-Diet-Information/BE pull request #34
Opened 2024-10-13 07:34 UTC by HongSeongJo

# 🚨 ISSUE
#25 
# 🔨 CHANGES
-data.sql 내 음식 저장 쿼리문 주석
-로컬 내 csv파일에 있는 음식 db에 저장
-csv파일 내에 있는 식단 db에 저장
-dormitory(기숙사) 이번 주 식단 확인 가능 (일요일 이후 주가 바뀌어서 안 뜨기 때문에 주기적으로 csv업데이트 해야함)
# 🪜 ADDITIONAL CONTEXT
lambda 이벤트 트리거로 csv파일 업로드 시 csv 경로를 spring 서버에 요청 -> 자동 업데이트
최적화 필요

2024-10-14 06:45 UTC, boroboro01 requested changes
정말 수고하셨습니다 👏🏻👏🏻👏🏻 아마 다른 기능에 비해 챌린지가 필요한 부분이라고 생각합니다.

서비스 핵심 로직이라 해당 부분의 중요도가 높아보입니다! 시간을 두고 계속 개선해도 좋을 것 같아요

보면서 코멘트 몇 개 남겼습니다 확인 부탁드려요!

2024-10-14 06:45 UTC, boroboro01 commented on src/main/java/com/kyonggi/diet/dietFood/service/Impl/DietFoodServiceImpl.java
> +     * @param name (String0
오타났어용~~

2024-10-14 06:45 UTC, boroboro01 commented on src/main/java/com/kyonggi/diet/dietFood/service/Impl/DietFoodServiceImpl.java
> +        }
중복 확인 로직이 생겼네요! 좋습니다

추후에 try-catch를 사용하여 save 실패시 로직 처리도 추가하는 것은 어떻게 생각하시나요?

2024-10-14 06:45 UTC, boroboro01 commented on src/main/java/com/kyonggi/diet/dietFile/CSVService.java
> +                    if (dietFoodService.checkExistByName(food)) {
csv 저장 전체 로직에 대해서 설명 및 결과 화면도 추가 해주시면 좋을 것 같습니다!

추가로 중복된 음식을 찾는 과정이 dietFoodService 내부에 존재하는 것으로 확인했는데 그럼 중복 확인을 두 번 진행하는 것은 아닌가요?

2024-10-14 06:45 UTC, boroboro01 commented on src/main/java/com/kyonggi/diet/dietFile/CSVController.java
> +            return;
파일이 존재하지 않는 경우 메세지가 필요할 것 같습니다!

2024-10-16 06:27 UTC, HongSeongJo commented on src/main/java/com/kyonggi/diet/dietFood/service/Impl/DietFoodServiceImpl.java
> +     * @param name (String0
어이쿠.. 혼자였으면 못 찾을뻔 했습니다 감사합니다 ㅎㅎ

2024-10-16 06:27 UTC, HongSeongJo commented on src/main/java/com/kyonggi/diet/dietFood/service/Impl/DietFoodServiceImpl.java
> +        }
try-catch로 exception 발생하고, 그 오류 메시지가 출력되도록 변경했습니다!

2024-10-16 06:29 UTC, HongSeongJo commented on src/main/java/com/kyonggi/diet/dietFile/CSVService.java
> +                    if (dietFoodService.checkExistByName(food)) {
어이쿠 중복 로직이 존재했군요 ..ㅎㅎ 바로 수정했습니다 감사합니다

2024-10-16 06:29 UTC, HongSeongJo commented on src/main/java/com/kyonggi/diet/dietFile/CSVController.java
> +            return;
후에 람다 적용을 통해 요청되는 api로 전환 예정이고, 이벤트가 발생하는 경우(csv 저장 된 경우)에만 요청이 와지는 것으로, 파일이 존재하지 않는 경우가 없다고 생각이 듭니다!

2024-10-16 16:04 UTC, boroboro01 commented on src/main/java/com/kyonggi/diet/dietFood/service/Impl/DietFoodServiceImpl.java
> +        }
좋습니다 👍🏻

2024-10-16 16:05 UTC, boroboro01 commented on src/main/java/com/kyonggi/diet/dietFile/CSVService.java
> +                    if (dietFoodService.checkExistByName(food)) {
빠른 수정 좋아요 🙂

2024-10-16 16:05 UTC, boroboro01 commented on src/main/java/com/kyonggi/diet/dietFile/CSVController.java
> +            return;
그 말도 맞네요! 파일이 존재하는 경우에만 Read/Write 이벤트가 발생하겠군요 확인했습니다!

2024-10-16 16:06 UTC, boroboro01 approved these changes
머지하겠습니다 수고하셨습니다 🔥

2024-10-16 16:06 UTC, merged